name: ChzzkMinecraftPlugin
version: 0.1.1
main: kr.kro.chzzk.minecraft.Main
description: Chzzk's Minecraft Plugin
author: Hyeonprojects
website: https://github.com/hyeonprojects/chzzk_minecraft
api-version: '1.21.8'

permissions:
  chzzk.user:
    description: "기본 사용 권한 (연결해서 사용할 사람)"
    default: true
  chzzk.link:
    description: "치지직 계정 연결 권한"
    default: true
  chzzk.unlink:
    description: "치지직 계정 연결 해제 권한"
    default: true
  chzzk.status:
    description: "치지직 연결 상태 확인 권한"
    default: true
  chzzk.admin:
    description: "관리자 권한"
    default: op


commands:
  chzzk:
    description: "치지직 마인크래프트 연동 명령어"
    usage: "/chzzk <link|unlink|status>"
    permission: chzzk.user
    aliases: ["치지직", "ㅊㅈㅈ"]